INSERT INTO rss_feeds VALUES
  ('http://rss.nytimes.com/services/xml/rss/nyt/World.xml',          'New York Times',      'United_States_of_America'),
  ('http://www.buenosairesherald.com/articles/rss.aspx',             'Buenos Aires Herald', 'Argentinia'),
  ('https://www.irishtimes.com/cmlink/news-1.1319192',               'Irish Times',         'Ireland'),
  ('http://rss.feedsportal.com/c/266/f/3503/index.rss',              'The Independent',     'United_Kingdom'),
  ('http://www.theguardian.com/world/rss',                           'The Guardian',        'United_Kingdom'),
  ('http://mondediplo.com/backend',                                  'Le Monde',            'France'),
  ('http://www.spiegel.de/international/index.rss',                  'Spiegel Online',      'Germany'),
  ('http://america.aljazeera.com/content/ajam/articles.rss',         'Al Jazeera',          'Qatar'),
  ('http://www.kyivpost.com/rss/',                                   'Kyiv Post',           'Ukraine'),
  ('http://feeds.feedburner.com/InternationalRss',                   'Haaretz',             'Israel'),
  ('http://www.hurriyetdailynews.com/rss.aspx',                      'Hurriyet',            'Turkey'),
  ('http://en.ria.ru/export/rss2/world/index.xml',                   'Ria Novosti',         'Russian_Federation'),
  ('http://timesofindia.feedsportal.com/c/33039/f/533917/index.rss', 'Times of India',      'India'),
  ('http://tribune.com.ng/news/world-news?format=feed',              'Nigerian Tribune',    'Nigeria'),
  ('http://www.thejakartaglobe.com/feed/',                           'Jakarta Globe',       'Indonesia')
